/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import GEtset.RepMarAutMasVendAnuSuc;
import GEtset.Sucursal;
import SQL.CRUDSQL;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HEIDER
 */
public class ReporteMarcaAutoMasVendidoAnualSucursal extends javax.swing.JFrame {
    CRUDSQL objcrud = new CRUDSQL();
    ArrayList <Sucursal> listaSucursalAux = new ArrayList<>();
    ArrayList <RepMarAutMasVendAnuSuc> listaAutosMasVendidosAnualSucursal = new ArrayList<>();
    DefaultTableModel modelo;
    
    public ReporteMarcaAutoMasVendidoAnualSucursal() {
        listaSucursalAux = objcrud.obtenerSucursales();
        initComponents();
        jTableTablaAutosMasVendidosAnualSucursal.setVisible(false);
        
        for(int i = 0 ; i < listaSucursalAux.size() ; i++){
            jComboBoxSucursalConsulta2.addItem(listaSucursalAux.get(i).getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAñoConsulta2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxSucursalConsulta2 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTablaAutosMasVendidosAnualSucursal = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabelSalir = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 80, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Año");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, -1, -1));

        jTextFieldAñoConsulta2.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldAñoConsulta2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextFieldAñoConsulta2.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldAñoConsulta2.setText(" ");
        jTextFieldAñoConsulta2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAñoConsulta2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldAñoConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 142, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Sucursal");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jComboBoxSucursalConsulta2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxSucursalConsulta2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBoxSucursalConsulta2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxSucursalConsulta2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jPanel1.add(jComboBoxSucursalConsulta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 142, -1));

        jButton2.setBackground(new java.awt.Color(0, 153, 153));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Generar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 149, 107, -1));

        jTableTablaAutosMasVendidosAnualSucursal.setBackground(new java.awt.Color(255, 255, 255));
        jTableTablaAutosMasVendidosAnualSucursal.setForeground(new java.awt.Color(0, 0, 0));
        jTableTablaAutosMasVendidosAnualSucursal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre marca", "Id marca", "Cantidad", "Estatus"
            }
        ));
        jScrollPane1.setViewportView(jTableTablaAutosMasVendidosAnualSucursal);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 450, 110));

        jPanel10.setBackground(new java.awt.Color(0, 153, 153));
        jPanel10.setForeground(new java.awt.Color(91, 233, 168));

        jLabelSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSalir.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalir.setText("    X");
        jLabelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalirMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Reporte de la marca de automotores mas vendidos por año - sucursal");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabelSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAñoConsulta2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAñoConsulta2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAñoConsulta2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Reportes().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(jComboBoxSucursalConsulta2.getSelectedItem().equals("") || jTextFieldAñoConsulta2.getText().equals("")){
            JOptionPane.showMessageDialog(null, "rellene los campos requeridos");
            jComboBoxSucursalConsulta2.setSelectedItem("");
            jTextFieldAñoConsulta2.setText("");
            jTableTablaAutosMasVendidosAnualSucursal.setVisible(false);
        }
        else{
            Object datos[] = new Object [5];
            String nombreSucursalAux = jComboBoxSucursalConsulta2.getSelectedItem() + "";
            String id_sucursal ="";
            String año = jTextFieldAñoConsulta2.getText();
            for(int i = 0 ; i < listaSucursalAux.size() ; i++){
                if(nombreSucursalAux.equals(listaSucursalAux.get(i).getNombre())){
                    id_sucursal = listaSucursalAux.get(i).getId_sucursal() + "";
                }
            }
            
            
            
            listaAutosMasVendidosAnualSucursal = objcrud.obtenerRepMarAutMasVendAnuSuc(año, id_sucursal);
            modelo = (new DefaultTableModel());            
            modelo.addColumn("Nombre_marca");
            modelo.addColumn("Id_marca");
            modelo.addColumn("Cantidad");
            modelo.addColumn("Estatus");
            
            for(int i = 0 ; i < listaAutosMasVendidosAnualSucursal.size() ; i++){                
                datos[0] = listaAutosMasVendidosAnualSucursal.get(i).getNombre_marca();
                datos[1] = listaAutosMasVendidosAnualSucursal.get(i).getId_marca();
                datos[2] = listaAutosMasVendidosAnualSucursal.get(i).getCantidad();                
                datos[3] = listaAutosMasVendidosAnualSucursal.get(i).getEstatus();  
                modelo.addRow(datos);
            }
            
            
            this.jTableTablaAutosMasVendidosAnualSucursal.setModel(modelo);
            this.jTableTablaAutosMasVendidosAnualSucursal.setVisible(true);
            int opc = JOptionPane.showConfirmDialog(rootPane, "Desea guardar el reporte en un archivo csv?");

        if (opc == JOptionPane.YES_OPTION) {
            try {
                BufferedWriter outStream = new BufferedWriter(new FileWriter("reporte_marca_automotores_mas_vendidos_por_anio_sucursal.csv", true));

                // Escribir datos
                for(int i = 0 ; i < listaAutosMasVendidosAnualSucursal.size() ; i++){                
                datos[0] = listaAutosMasVendidosAnualSucursal.get(i).getNombre_marca();
                datos[1] = listaAutosMasVendidosAnualSucursal.get(i).getId_marca();
                datos[2] = listaAutosMasVendidosAnualSucursal.get(i).getCantidad();                
                datos[3] = listaAutosMasVendidosAnualSucursal.get(i).getEstatus();
                    outStream.write(datos[0] + " , " + datos[1] + " , " + datos[2] + " , " + datos[3]  +  "\n");

                }
                outStream.close();
                JOptionPane.showMessageDialog(null, "Datos guardados en reporte_marca_automotores_mas_vendidos_por_anio_sucursal.csv");
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al guardar en el archivo CSV");
            }
        }
            
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalirMouseClicked
        JOptionPane.showMessageDialog(null, "Gracias por usar nuestro sistema\nTenga un buen día");
        System.exit(0);
    }//GEN-LAST:event_jLabelSalirMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteMarcaAutoMasVendidoAnualSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteMarcaAutoMasVendidoAnualSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteMarcaAutoMasVendidoAnualSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteMarcaAutoMasVendidoAnualSucursal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteMarcaAutoMasVendidoAnualSucursal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxSucursalConsulta2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTablaAutosMasVendidosAnualSucursal;
    private javax.swing.JTextField jTextFieldAñoConsulta2;
    // End of variables declaration//GEN-END:variables
}
