/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import GEtset.RepEmpleados;
import GEtset.RepMarAutMasVendAnuSuc;
import GEtset.Sucursal;
import SQL.CRUDSQL;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HEIDER
 */
public class ReporteEmpleados extends javax.swing.JFrame {

    CRUDSQL objcrud = new CRUDSQL();
    ArrayList<RepEmpleados> listaReporteEmpleados = new ArrayList<>();
    DefaultTableModel modelo;

    public ReporteEmpleados() {
        initComponents();
        jTablReporteEmpleados.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablReporteEmpleados = new javax.swing.JTable();
        jButtonVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabelSalir4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablReporteEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        jTablReporteEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTablReporteEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        jTablReporteEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablReporteEmpleados);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 830, 290));

        jButtonVolver.setBackground(new java.awt.Color(0, 153, 153));
        jButtonVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonVolver.setForeground(new java.awt.Color(0, 0, 0));
        jButtonVolver.setText("Volver");
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, 80, 40));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabelSalir4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSalir4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalir4.setText("    X");
        jLabelSalir4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalir4MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Reporte de los empleados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 332, Short.MAX_VALUE)
                .addComponent(jLabelSalir4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelSalir4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 90));

        jButtonGenerar.setBackground(new java.awt.Color(0, 153, 153));
        jButtonGenerar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonGenerar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonGenerar.setText("Generar");
        jButtonGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGenerar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 410, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSalir4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalir4MouseClicked
        JOptionPane.showMessageDialog(null, "Gracias por usar nuestro sistema\nTenga un buen día");
        System.exit(0);
    }//GEN-LAST:event_jLabelSalir4MouseClicked

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        this.setVisible(false);
        new Reportes().setVisible(true);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarActionPerformed

        listaReporteEmpleados = objcrud.obtenerRepEmpleados();
        Object datos[] = new Object[10];

        modelo = (new DefaultTableModel());
        modelo.addColumn("Nombre_sucursal");
        modelo.addColumn("Nombre_cargo");
        modelo.addColumn("Documento");
        modelo.addColumn("Nombre_empleado");
        modelo.addColumn("Salario");
        modelo.addColumn("Codigo_empleado");
        modelo.addColumn("Fecha_nacimiento");
        modelo.addColumn("Fecha_ingreso");
        modelo.addColumn("Id_sucursal");
        modelo.addColumn("Id_cargo");

        for (int i = 0; i < listaReporteEmpleados.size(); i++) {
            datos[0] = listaReporteEmpleados.get(i).getNombre_sucursal();
            datos[1] = listaReporteEmpleados.get(i).getNombre_cargo();
            datos[2] = listaReporteEmpleados.get(i).getDocumento();
            datos[3] = listaReporteEmpleados.get(i).getNombre_empleado();
            datos[4] = listaReporteEmpleados.get(i).getSalario();
            datos[5] = listaReporteEmpleados.get(i).getCodigo();
            datos[6] = listaReporteEmpleados.get(i).getFecha_nacimiento();
            datos[7] = listaReporteEmpleados.get(i).getFecha_ingreso();
            datos[8] = listaReporteEmpleados.get(i).getId_sucursal();
            datos[9] = listaReporteEmpleados.get(i).getId_cargo();
            modelo.addRow(datos);
        }
        this.jTablReporteEmpleados.setModel(modelo);
        this.jTablReporteEmpleados.setVisible(true);

        int opc = JOptionPane.showConfirmDialog(rootPane, "Desea guardar el reporte en un archivo csv?");

        if (opc == JOptionPane.YES_OPTION) {
            try {
                BufferedWriter outStream = new BufferedWriter(new FileWriter("reporte_empleados.csv", true));

                // Escribir datos
                for (int i = 0; i < listaReporteEmpleados.size(); i++) {
                    datos[0] = listaReporteEmpleados.get(i).getNombre_sucursal();
                    datos[1] = listaReporteEmpleados.get(i).getNombre_cargo();
                    datos[2] = listaReporteEmpleados.get(i).getDocumento();
                    datos[3] = listaReporteEmpleados.get(i).getNombre_empleado();
                    datos[4] = listaReporteEmpleados.get(i).getSalario();
                    datos[5] = listaReporteEmpleados.get(i).getCodigo();
                    datos[6] = listaReporteEmpleados.get(i).getFecha_nacimiento();
                    datos[7] = listaReporteEmpleados.get(i).getFecha_ingreso();
                    datos[8] = listaReporteEmpleados.get(i).getId_sucursal();
                    datos[9] = listaReporteEmpleados.get(i).getId_cargo();
                    outStream.write(datos[0] + " , " + datos[1] + " , " + datos[2] + " , " + datos[3] + " , " + datos[4] + datos[5] + datos[6] + datos[7] + datos[8] + datos[9] + "\n");

                }
                outStream.close();
                JOptionPane.showMessageDialog(null, "Datos guardados en reporte_empleados.csv");
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al guardar en el archivo CSV");
            }
        }
    }//GEN-LAST:event_jButtonGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGenerar;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelSalir4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablReporteEmpleados;
    // End of variables declaration//GEN-END:variables
}
