/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import GEtset.RepCliNueNac;
import GEtset.RepMarAutMasVendAnuSuc;
import GEtset.Sucursal;
import SQL.CRUDSQL;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HEIDER
 */
public class ReporteClientesNuevosNacional extends javax.swing.JFrame {

    CRUDSQL objcrud = new CRUDSQL();
    ArrayList<RepCliNueNac> listaClientesNuevosNacional = new ArrayList<>();

    DefaultTableModel modelo;

    public ReporteClientesNuevosNacional() {
        initComponents();
        this.jTableConsulta1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBoxMesConsulta1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldAñoConsulta1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabelSalir4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsulta1 = new javax.swing.JTable();
        jButtonGenerarReporteClientesNuevosNacional = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelCantidadClientesNuevos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Volver");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 100, 30));

        jComboBoxMesConsulta1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxMesConsulta1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel1.add(jComboBoxMesConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Año");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jTextFieldAñoConsulta1.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldAñoConsulta1.setText(" ");
        jTextFieldAñoConsulta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAñoConsulta1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldAñoConsulta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 94, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabelSalir4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSalir4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalir4.setText("    X");
        jLabelSalir4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalir4MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Reporte de los clientes nuevos a nivel nacional");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabelSalir4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelSalir4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 49, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        jTableConsulta1.setBackground(new java.awt.Color(255, 255, 255));
        jTableConsulta1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTableConsulta1.setForeground(new java.awt.Color(0, 0, 0));
        jTableConsulta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Documento", "Nombre", "id_ciudad", "fecha_inicio", "id_sucursal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableConsulta1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 400, 130));

        jButtonGenerarReporteClientesNuevosNacional.setBackground(new java.awt.Color(0, 153, 153));
        jButtonGenerarReporteClientesNuevosNacional.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonGenerarReporteClientesNuevosNacional.setForeground(new java.awt.Color(0, 0, 0));
        jButtonGenerarReporteClientesNuevosNacional.setText("Generar");
        jButtonGenerarReporteClientesNuevosNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGenerarReporteClientesNuevosNacionalActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonGenerarReporteClientesNuevosNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 100, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cantidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        jLabelCantidadClientesNuevos.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelCantidadClientesNuevos.setForeground(new java.awt.Color(0, 0, 0));
        jLabelCantidadClientesNuevos.setText("Vacio");
        jPanel1.add(jLabelCantidadClientesNuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGenerarReporteClientesNuevosNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGenerarReporteClientesNuevosNacionalActionPerformed
        String mes = "";
        String año = "";
        String numMes = "";
        Object datos[] = new Object[5];
        if (jComboBoxMesConsulta1.getSelectedItem().equals("") || jTextFieldAñoConsulta1.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "inserte los campos nesesarios");
            jComboBoxMesConsulta1.setSelectedItem("");
            jTextFieldAñoConsulta1.setText("");
            jTableConsulta1.setVisible(false);
        } else {

            mes = jComboBoxMesConsulta1.getSelectedItem() + "";
            año = jTextFieldAñoConsulta1.getText();
            numMes = objcrud.ConvertirMesANumero(mes);

            listaClientesNuevosNacional = objcrud.obtenerRepCliNueNac(año, numMes);
            String cantidad = objcrud.obtenerCantidadRepCliNueNac(año, numMes);

            modelo = (new DefaultTableModel());
            modelo.addColumn("Documento");
            modelo.addColumn("Nombre");
            modelo.addColumn("id_ciudad");
            modelo.addColumn("fecha_inicio");
            modelo.addColumn("id_sucursal");

            for (int i = 0; i < listaClientesNuevosNacional.size(); i++) {
                datos[0] = listaClientesNuevosNacional.get(i).getDocumento();
                datos[1] = listaClientesNuevosNacional.get(i).getNombre();
                datos[2] = listaClientesNuevosNacional.get(i).getId_ciudad();
                datos[3] = listaClientesNuevosNacional.get(i).getFecha_inicio();
                datos[4] = listaClientesNuevosNacional.get(i).getId_sucursal();
                modelo.addRow(datos);
            }

            this.jLabelCantidadClientesNuevos.setText(cantidad);
            this.jTableConsulta1.setModel(modelo);
            this.jTableConsulta1.setVisible(true);
            int opc = JOptionPane.showConfirmDialog(rootPane, "Desea guardar el reporte en un archivo csv?");

            if (opc == JOptionPane.YES_OPTION) {
                try {
                    BufferedWriter outStream = new BufferedWriter(new FileWriter("reporte_clientes_nuevos_nivelNacional.csv", true));

                    // Escribir datos
                    for (int i = 0; i < listaClientesNuevosNacional.size(); i++) {
                        datos[0] = listaClientesNuevosNacional.get(i).getDocumento();
                        datos[1] = listaClientesNuevosNacional.get(i).getNombre();
                        datos[2] = listaClientesNuevosNacional.get(i).getId_ciudad();
                        datos[3] = listaClientesNuevosNacional.get(i).getFecha_inicio();
                        datos[4] = listaClientesNuevosNacional.get(i).getId_sucursal();
                        outStream.write(datos[0] + " , " + datos[1] + " , " + datos[2] + " , " + datos[3] + " , " + datos[4] + "\n");

                    }
                    outStream.close();
                    JOptionPane.showMessageDialog(null, "Datos guardados en reporte_clientes_nuevos_nivelNacional.csv");
                } catch (IOException e) {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error al guardar en el archivo CSV");
                }
            }

        }
    }//GEN-LAST:event_jButtonGenerarReporteClientesNuevosNacionalActionPerformed

    private void jLabelSalir4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalir4MouseClicked
        JOptionPane.showMessageDialog(null, "Gracias por usar nuestro sistema\nTenga un buen día");
        System.exit(0);
    }//GEN-LAST:event_jLabelSalir4MouseClicked

    private void jTextFieldAñoConsulta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAñoConsulta1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAñoConsulta1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        new Reportes().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteClientesNuevosNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteClientesNuevosNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteClientesNuevosNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteClientesNuevosNacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteClientesNuevosNacional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonGenerarReporteClientesNuevosNacional;
    private javax.swing.JComboBox<String> jComboBoxMesConsulta1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCantidadClientesNuevos;
    private javax.swing.JLabel jLabelSalir4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsulta1;
    private javax.swing.JTextField jTextFieldAñoConsulta1;
    // End of variables declaration//GEN-END:variables
}
