/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Josed
 */
public class Reportes extends javax.swing.JFrame {

    /**
     * Creates new form Consulta
     */
    public Reportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabelSalir4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBttnClientesNuevosNacional = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBttnVentasMensual = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jBttnVentasAnual = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jBttnClientesNuevos = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jBttnMArcaCarrosCompradosSucursal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jBttnDatosEmpleados = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jBttnMArcaCarrosCompradosNacional = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setBackground(new java.awt.Color(0, 153, 153));
        btnVolver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnVolver.setForeground(new java.awt.Color(0, 0, 0));
        btnVolver.setText("Inicio");
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 80, 40));

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setForeground(new java.awt.Color(91, 233, 168));

        jLabelSalir4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelSalir4.setForeground(new java.awt.Color(0, 0, 0));
        jLabelSalir4.setText("    X");
        jLabelSalir4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSalir4MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Reportes");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap(310, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263)
                .addComponent(jLabelSalir4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                    .addComponent(jLabelSalir4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 60));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Reporte de la cantidad de clientes nuevos a nivel nacional. ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 400, -1));

        jBttnClientesNuevosNacional.setBackground(new java.awt.Color(0, 153, 153));
        jBttnClientesNuevosNacional.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBttnClientesNuevosNacional.setForeground(new java.awt.Color(0, 0, 0));
        jBttnClientesNuevosNacional.setText("Generar");
        jBttnClientesNuevosNacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBttnClientesNuevosNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnClientesNuevosNacionalActionPerformed(evt);
            }
        });
        jPanel1.add(jBttnClientesNuevosNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 100, 30));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Reporte de marca con mayor cantidad de ventas mensual por sucursal. ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jBttnVentasMensual.setBackground(new java.awt.Color(0, 153, 153));
        jBttnVentasMensual.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBttnVentasMensual.setForeground(new java.awt.Color(0, 0, 0));
        jBttnVentasMensual.setText("Generar");
        jBttnVentasMensual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBttnVentasMensual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnVentasMensualActionPerformed(evt);
            }
        });
        jPanel1.add(jBttnVentasMensual, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 100, 30));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Reporte de marca con mayor cantidad de ventas anual por sucursal. ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 390, -1));

        jBttnVentasAnual.setBackground(new java.awt.Color(0, 153, 153));
        jBttnVentasAnual.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBttnVentasAnual.setForeground(new java.awt.Color(0, 0, 0));
        jBttnVentasAnual.setText("Generar");
        jBttnVentasAnual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBttnVentasAnual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnVentasAnualActionPerformed(evt);
            }
        });
        jPanel1.add(jBttnVentasAnual, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 170, 100, 30));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Reporte de datos sobre los clientes nuevos. ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 380, -1));

        jBttnClientesNuevos.setBackground(new java.awt.Color(0, 153, 153));
        jBttnClientesNuevos.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBttnClientesNuevos.setForeground(new java.awt.Color(0, 0, 0));
        jBttnClientesNuevos.setText("Generar");
        jBttnClientesNuevos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBttnClientesNuevos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnClientesNuevosActionPerformed(evt);
            }
        });
        jPanel1.add(jBttnClientesNuevos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 100, 30));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Reporte de la marca de carros mas comprados en un mes particular a nivel Nacional ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jBttnMArcaCarrosCompradosSucursal.setBackground(new java.awt.Color(0, 153, 153));
        jBttnMArcaCarrosCompradosSucursal.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBttnMArcaCarrosCompradosSucursal.setForeground(new java.awt.Color(0, 0, 0));
        jBttnMArcaCarrosCompradosSucursal.setText("Generar");
        jBttnMArcaCarrosCompradosSucursal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBttnMArcaCarrosCompradosSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnMArcaCarrosCompradosSucursalActionPerformed(evt);
            }
        });
        jPanel1.add(jBttnMArcaCarrosCompradosSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 100, 30));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Reporte de los datos de los empleados. ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jBttnDatosEmpleados.setBackground(new java.awt.Color(0, 153, 153));
        jBttnDatosEmpleados.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBttnDatosEmpleados.setForeground(new java.awt.Color(0, 0, 0));
        jBttnDatosEmpleados.setText("Generar");
        jBttnDatosEmpleados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBttnDatosEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnDatosEmpleadosActionPerformed(evt);
            }
        });
        jPanel1.add(jBttnDatosEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 340, 100, 30));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Reporte de la marca de carros mas comprados en un mes particular por sucursal. ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 470, -1));

        jBttnMArcaCarrosCompradosNacional.setBackground(new java.awt.Color(0, 153, 153));
        jBttnMArcaCarrosCompradosNacional.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jBttnMArcaCarrosCompradosNacional.setForeground(new java.awt.Color(0, 0, 0));
        jBttnMArcaCarrosCompradosNacional.setText("Generar");
        jBttnMArcaCarrosCompradosNacional.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jBttnMArcaCarrosCompradosNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnMArcaCarrosCompradosNacionalActionPerformed(evt);
            }
        });
        jPanel1.add(jBttnMArcaCarrosCompradosNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelSalir4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSalir4MouseClicked
        JOptionPane.showMessageDialog(null, "Gracias por usar nuestro sistema\nTenga un buen día");
        System.exit(0);
    }//GEN-LAST:event_jLabelSalir4MouseClicked

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.setVisible(false);
        new Inicio().setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jBttnClientesNuevosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnClientesNuevosActionPerformed
        this.setVisible(false);
        new ReporteDatosClientesNuevos().setVisible(true);
    }//GEN-LAST:event_jBttnClientesNuevosActionPerformed

    private void jBttnClientesNuevosNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnClientesNuevosNacionalActionPerformed
 this.setVisible(false);
        new ReporteClientesNuevosNacional().setVisible(true);
    }//GEN-LAST:event_jBttnClientesNuevosNacionalActionPerformed

    private void jBttnVentasMensualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnVentasMensualActionPerformed
       this.setVisible(false);
        new ReporteMarcaAutoMasVendidoMensualSucursal().setVisible(true);
    }//GEN-LAST:event_jBttnVentasMensualActionPerformed

    private void jBttnVentasAnualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnVentasAnualActionPerformed
        this.setVisible(false);
        new ReporteMarcaAutoMasVendidoAnualSucursal().setVisible(true);
    }//GEN-LAST:event_jBttnVentasAnualActionPerformed

    private void jBttnMArcaCarrosCompradosSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnMArcaCarrosCompradosSucursalActionPerformed
        this.setVisible(false);
        new ReporteMarcaAutoNuevoMasVendidoMensualSucursal().setVisible(true);
    }//GEN-LAST:event_jBttnMArcaCarrosCompradosSucursalActionPerformed

    private void jBttnDatosEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnDatosEmpleadosActionPerformed
        this.setVisible(false);
        new ReporteEmpleados().setVisible(true);
    }//GEN-LAST:event_jBttnDatosEmpleadosActionPerformed

    private void jBttnMArcaCarrosCompradosNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnMArcaCarrosCompradosNacionalActionPerformed
        this.setVisible(false);
        new ReporteMarcaAutoNuevoMasVendidoMensualNacional().setVisible(true);
    }//GEN-LAST:event_jBttnMArcaCarrosCompradosNacionalActionPerformed


    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jBttnClientesNuevos;
    private javax.swing.JButton jBttnClientesNuevosNacional;
    private javax.swing.JButton jBttnDatosEmpleados;
    private javax.swing.JButton jBttnMArcaCarrosCompradosNacional;
    private javax.swing.JButton jBttnMArcaCarrosCompradosSucursal;
    private javax.swing.JButton jBttnVentasAnual;
    private javax.swing.JButton jBttnVentasMensual;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelSalir4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
